[project]
name = "parlabert"
version = "0.1.0"
description = "ParlaBERT classifies political statements by assigning them to a Swiss political party"
readme = "README.md"
authors = [
    { name = "Jonathan", email = "github.departure288@passmail.net" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pyreadr>=0.5.6",
    "requests>=2.34.2",
]

[project.scripts]
parlabert = "parlabert:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "ruff>=0.16.7",
]

[tool.poe.tasks]
lint = "ruff check ."
format = "ruff format ."
fix = "ruff check . --fix"
all = ["fix", "format"]
